name: Publish to npm

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: Setup pnpm
        uses: pnpm/setup@v2
        with:
          version: 11
          runtime: node@24
          cache: false

      - name: Publish to npm
        run: pnpm publish --provenance --access public --no-git-checks
